name: generate ascii artwork
on: 
  push
jobs:
  ascii-script_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: list files
        run: ls -ltra

      - name: ascii script

        run: ./.github/workflows/ascii-script.sh
