name: generate ascii artwork
on: 
  push
jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
<<<<<<< HEAD
        uses: actions/checkout@v4
=======
        uses: actions/checkout@v4
>>>>>>> a82bb755b4ef522946e5578353c4c11956a73f8e

      - name: install coysay program
        run: sudo apt-get install cowsay -y

      - name: Execute cowsay CMD
        run: cowsay -f dragon "run for the cover iam dragon" >> dragon.txt

      - name: test file exist
        run: grep -i "dragon" dragon.txt
    
      - name: read file
        run: cat dragon.txt

      - name: list files
        run: ls -ltra
      

         


